# Generated by Django 4.2.27 on 2026-01-16 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модуля')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('instruction', models.TextField(blank=True, help_text='Общее описание задания модуля', verbose_name='Общая инструкция')),
                ('duration', models.CharField(blank=True, help_text='Например: 2 часа', max_length=50, verbose_name='Рекомендуемое время')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='Максимальный балл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['section', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер шага')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок шага')),
                ('description', models.TextField(help_text='Подробное описание того, что нужно сделать', verbose_name='Описание шага')),
                ('expected_result', models.TextField(blank=True, verbose_name='Ожидаемый результат')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='modules.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Шаг модуля',
                'verbose_name_plural': 'Шаги модулей',
                'ordering': ['module', 'order', 'number'],
                'unique_together': {('module', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StepNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('tip', 'Совет'), ('important', 'Важно'), ('example', 'Пример')], default='info', max_length=20, verbose_name='Тип заметки')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='modules.modulestep', verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'Заметка к шагу',
                'verbose_name_plural': 'Заметки к шагам',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название файла')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='modules/files/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('document', 'Документ'), ('image', 'Изображение'), ('archive', 'Архив'), ('video', 'Видео'), ('other', 'Другое')], default='document', max_length=20, verbose_name='Тип файла')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='modules.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Файл модуля',
                'verbose_name_plural': 'Файлы модулей',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='modules.section', verbose_name='Раздел'),
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название критерия')),
                ('description', models.TextField(blank=True, verbose_name='Описание критерия')),
                ('max_score', models.PositiveIntegerField(verbose_name='Максимальный балл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='modules.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Критерий оценивания',
                'verbose_name_plural': 'Критерии оценивания',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершен')], default='not_started', max_length=20, verbose_name='Статус')),
                ('current_step', models.PositiveIntegerField(default=1, verbose_name='Текущий шаг')),
                ('notes', models.TextField(blank=True, verbose_name='Личные заметки')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='modules.module', verbose_name='Модуль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс по модулю',
                'verbose_name_plural': 'Прогресс по модулям',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
