# Generated by Django 4.2.27 on 2026-01-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='modules/steps/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='modules.modulestep', verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'Изображение шага',
                'verbose_name_plural': 'Изображения шагов',
                'ordering': ['order'],
            },
        ),
    ]
