# Generated by Django 4.2.27 on 2026-01-23 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_stepimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='task_condition',
            field=models.TextField(blank=True, help_text='Текст задания из PDF экзамена', verbose_name='Условие задания'),
        ),
        migrations.AddField(
            model_name='module',
            name='task_number',
            field=models.CharField(blank=True, help_text='Например: 1.1, 2.3', max_length=20, verbose_name='Номер задания'),
        ),
        migrations.AddField(
            model_name='section',
            name='session_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер сессии'),
        ),
        migrations.CreateModel(
            name='ExamVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Например: КОД 1.2', max_length=50, verbose_name='Код экзамена')),
                ('variant_number', models.PositiveIntegerField(verbose_name='Номер варианта')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание предметной области')),
                ('description_file', models.FileField(blank=True, null=True, upload_to='exams/descriptions/', verbose_name='PDF описания')),
                ('task_file', models.FileField(blank=True, null=True, upload_to='exams/tasks/', verbose_name='PDF задания')),
                ('total_time', models.CharField(blank=True, help_text='Например: 6 часов 30 минут', max_length=50, verbose_name='Общее время')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Вариант экзамена',
                'verbose_name_plural': 'Варианты экзаменов',
                'ordering': ['order', 'code', 'variant_number'],
                'unique_together': {('code', 'variant_number')},
            },
        ),
        migrations.AddField(
            model_name='section',
            name='exam_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='modules.examvariant', verbose_name='Вариант экзамена'),
        ),
    ]
